[pytest]
# Opzioni generali
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Output
verbose = 1
addopts = --tb=short -v --cov=./ --cov-report=term-missing --cov-report=html

# Ignora file specifici
ignore = __pycache__

# Markers
markers =
    slow: test lento
    integration: test di integrazione
    unit: test unitario
